name: pokedex_final_proyect
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.8
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/pokeball.png
    - assets/pokeballblack.png
    - assets/pokedex.png
    - assets/alturaicon.png
    - assets/pesoicon.png
  uses-material-design: true
